use_frameworks!

target 'CreolePriceSelectionView_Example' do
  pod 'CreolePriceSelectionView', :path => '../'
  pod 'iCarousel'
  
  target 'CreolePriceSelectionView_Tests' do
    inherit! :search_paths

    
  end
end
